### ISSUE TITLE
Program type already present: com.arellomobile.mvp.GenerateViewState

### ISSUE THREAD

**Issue by AlexeyKorshun** [jordan1997/Moxy#1]
Доброго дня, пытался переехать на ваш репозиторий и столкнулся с проблемой

При попытки build gradle выдает ошибку 

```
com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
 Program type already present: com.arellomobile.mvp.GenerateViewState
```

посмотрев в зависимости увидел такие 2 jar 
![screenshot](https://user-images.githubusercontent.com/7361026/52353759-5c451d00-2a59-11e9-936d-b4fcfc9f6519.png)

которые идентичны.
Зависимость на tech.schoolhelper:moxy:1.5.6@jar идет от implementation 'tech.schoolhelper:moxy-x-androidx:1.5.6'
Вероятно проблема где то в конфигурации публикации.

**Comment by AlexeyKorshun** [comment]
Временное решение исключение `implementation 'tech.schoolhelper:moxy-x:1.5.6'` из зависимостей.

**Comment by jordan1997** [comment]
Please provide your dependencies block?

**Comment by AlexeyKorshun** [comment]
depndencies {
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    implementation 'tech.schoolhelper:moxy-x:1.5.6'
    kapt 'tech.schoolhelper:moxy-x-compiler:1.5.6'
    implementation 'tech.schoolhelper:moxy-x-androidx:1.5.6'
}

**Comment by jordan1997** [comment]
I will try to fix this on weekend, use the tmp solution at the moment.

**Comment by jordan1997** [comment]
I found the problem, I will change the artifact name, to moxyx or something else.

**Comment by AlexeyKorshun** [comment]
Maybe you can use `compileOnly` instead of https://github.com/jordan1997/Moxy/blob/develop/moxy-androidx/build.gradle#L240

**Comment by jordan1997** [comment]
I fixed your issue, try to use the following dependencies:
```
implementation 'tech.schoolhelper:moxy-x:1.5.7'
implementation 'tech.schoolhelper:moxy-x-androidx:1.5.7'
kapt 'tech.schoolhelper:moxy-x-compiler:1.5.7'
```
