### ISSUE TITLE
MvpAppCompatDialogFragment is missing

### ISSUE THREAD

**Issue by AlexTsyganov** [jordan1997/Moxy#2]
Can you please fix the package in file:

`Moxy/moxy-androidx/src/main/java/com/arellomobile/mvp/MvpAppCompatDialogFragment.java`

From `package com.alfaenzo.alfa.presentation.base;` to `package com.arellomobile.mvp;`

Thanks

**Comment by jordan1997** [comment]
Fixed

**Comment by AlexTsyganov** [comment]
Can you please submit the new version to `Maven`?

Thanks

**Comment by jordan1997** [comment]
Yep, I have plan to release new version on this weekend, with fix for #1
